### ISSUE TITLE
non-default CGA styles do not work

### ISSUE THREAD

**Issue by mistafunk** [Esri/palladio#106]
this rule only generates correctly, if the style is set to "default":

```
version "2018.1"

attr height = rand(15,25)
attr x = 1.5

@StartRule
Init -->
  extrude(height * x)

style Style1
attr x = 1.0

style Style2
attr x = 2.0
```

**Comment by MattB3D** [comment]
Ohhh, the good ol' styles ...

**Comment by mistafunk** [comment]
The problem is pretty clear, we're trying to use a start rule e.g. "Style1$Init" which does not exist (only the "x" attr has style in above example).

In the assign node, we need to evaluate the default rule attribute values, but filter for the active style.
As RPKs only support one start rule at the moment, we should limit Palladio to only support "Default" start rules.

**Comment by mistafunk** [comment]
implemented basic workaround in slightly mis-named branch "fix-cga-style-support", i.e. we only support different attribute default values per style. for full CGA style support we need to wait for PRT itself to support it in the API.

**Comment by mistafunk** [comment]
closing this for now, we cannot do more without significant support in the PRT API itself.
