### ISSUE TITLE
add easy manipulation of CGA rule attributes ("smart" attribute create)

### ISSUE THREAD

**Issue by mistafunk** [Esri/palladio#123]
In 1.6, pldAssign was emitting all attributes with default values as primitive attributes. This was wrong and will prevent more complex rule sets with inter-dependent rule attributes to work correctly (e.g. "year" attribute of the CityEngine "Paris" example can not be changed correctly).

A fix of the above is easy, simply remove writing the prim attrs (will be done in 1.7). But this makes overriding attributes even harder (how to find the correct attribute name and type, which is not always trivial to derive from the CGA rules due to some character restrictions in Houdini attribute names).

We need a simple way for users to manipulate rule attributes on primitives. This process is currently not simple:
1. drop "attribute create" node between pldAssign and pldGenerate
1. back in CityEngine (in the inspector and/or looking at the CGA code) find the available attribute to change
1. figure out some of the renaming quirks (e.g. the slash from CGA rule imports is turned into double underscore) (!)
1. finally set type and value to overwrite the rule attribute

Clearly this does not fly. Therefore enhance pldAssign with an "override" mode which reads the current primitive attribute values for "pldRPK", "pldStartRule", ... and provide UI controls for each detected RPK/start rule combination (the incoming geo might have multiple values for pldRPK etc)

**Comment by Top61ly** [comment]
So, could you please tell me how to change CGA attribute in palladio v1.7.0?

**Comment by mistafunk** [comment]
In 1.7, the priniciple is still the same as before, we just do not create primitive attributes for default rule attributes anymore.

So as before, use an "Attribute Create" node between pldAssign and pldGenerate:
1. Set 'class' to "Primitive"
1. Set 'type' to "Float" for CGA number attribute, "String" for CGA strings and "Int" for CGA booleans

Hope this helps?

**Comment by mistafunk** [comment]
(internal ticket CE-8047)

**Comment by mistafunk** [comment]
In 2.0 we've added an inspector for rule attrs.
