### ISSUE TITLE
Can't find "pldxxx" node in Houdini

### ISSUE THREAD

**Issue by Top61ly** [Esri/palladio#135]
Windows
Houdini FX 17.5.391
Pre-Built Palladio 1.6.3
No license

1.Create a new "dso" folder under "C:/Users/MyUserName/houdini17.5/".
2.Extract into that directory.
3.Reopen a new Houdini Project, but I cant find the new two nodes.

Could you please tell me which step is wrong?

**Comment by mistafunk** [comment]
make sure the palladio.dll is directly in the dso subdirectory, there must not be an intermediate directory in between.

also, you could try to set HOUDINI_DSO_ERROR environment variable to a value of 2 or 3 and check the output for "palladio" (also see https://www.sidefx.com/docs/houdini/ref/env.html)

**Comment by mistafunk** [comment]
Additionally, also make sure the "dso" folder you created is added to the PATH environment variable (we are working to avoid this requirement in the future).

**Comment by Top61ly** [comment]
After I added the "dso" folder into the PATH environment variable, it worked.

I found "Note: it is NOT necessary to modify the system PATH environment variable." in "Quick Start".

I think it need to be fixed.
