### ISSUE TITLE
Invalid rule package filepath shows error on pldAssign node (instead of pldGenerate node)

### ISSUE THREAD

**Issue by jobertuefer** [Esri/palladio#159]
Currently the filepath gets checked on the pldGenerate node, so when an invalid filepath is assigned on pldAssign and error is shown at the pldGenerate node. It would be clearer to check for a valid filepath on pldAssign node and also show the error on that node.

![pldFilePath2](https://user-images.githubusercontent.com/72210189/95055471-99145c00-06f3-11eb-9339-7d0c88759c98.jpg)

**Comment by mistafunk** [comment]
Merged for v1.9.0
