### ISSUE TITLE
Implement CityEngine shader based on CGA material attrs

### ISSUE THREAD

**Issue by MattB3D** [Esri/palladio#27]
Currently, all material attributes are stored in the resulting model as primitive-attrs.

In the CE-Node, we would like to provide a generic 'CE shader' that maps these CGA material attributes to a standard material in Houdini, to match the look as close as possible to the CE shader (same logic, e.g. "color x texture x dirtmap" )

This hardcoded mapping of the attributes is supposed to be an example for users that wand to map to their own shaders.

Options of implementation of this mapping:
- VEX (?)
- VopSOP (?)
- Visual Scripting Tool (?)

**Comment by mistafunk** [comment]
closing this, let's redirect material/shader questions to the example scene (to be updated soon)...
