### ISSUE TITLE
Attributed street shape import via alembic

### ISSUE THREAD

**Issue by MattB3D** [Esri/palladio#28]
## Question:

Is the following possible?
If so, we could change this to a proper enhancement issue.
## Idea: Plug-and-play workflow of:
- CityEngine street shape export (with all attributes like seed, streetEdges, OID, ..) to alembic [ solved ? ]
- in Houdini: create per-shape (or OID) the delimiter attribute
- pipe all those 'ex CE dynamic' shapes directly into our CE Node so that e.g. streetEdges are properly evaluated.

==> Use CE's Dynamic City Layouts to layout city, then export the layout to Houdini, where the city is built.

**Comment by mistafunk** [comment]
closing this - this is not a core concern for palladio itself
