### ISSUE TITLE
add support for macOS

### ISSUE THREAD

**Issue by mistafunk** [Esri/palladio#91]

**Comment by wandergis** [comment]
That's awesome!!!

**Comment by mistafunk** [comment]
the macos branch got a bit behind... how important is mac support for you?

**Comment by mistafunk** [comment]
CityEngine SDK / PRT is currently not available anymore for macOS, so we have to abandon macOS support for the immediate future. (The hope is that PRT will reappear for Apple Silicon at some point and we can pick this up again.)
